blank_issues_enabled: false
contact_links:
  - name: Question about this project
    url: https://github.com/orgs/asirobots/discussions
    about: For general questions that aren't a specific artifact/tooling issue.
